# Generated by Django 4.2.16 on 2026-05-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('dropped', 'Dropped')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='manga',
            options={'ordering': ['chapter_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='manga',
            name='chapter_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='manga',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('done', 'Done'), ('dropped', 'Dropped')], default='planned', max_length=20),
        ),
        migrations.AddField(
            model_name='manga',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga_api.series'),
        ),
    ]
