# Generated by Django 4.2.16 on 2026-05-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0002_series_alter_manga_options_manga_chapter_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pages_read', models.IntegerField(default=0)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='manga_api.manga')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('manga', 'date')},
            },
        ),
    ]
