# Generated by Django 4.2.16 on 2026-05-28 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0003_readinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='translated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
