# Generated by Django 4.2.16 on 2026-05-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0004_page_translated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
