# Generated by Django 4.2.16 on 2026-06-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga_api', '0006_add_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='custom_cover',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='custom_cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
